In [1]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr + 1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
arr = np.random.randint(5, 50, size=12)

print(arr.min())
print(arr.max())

10
42


In [ ]:
arr = np.random.randint(1, 10, size=(3 , 4))
print(arr)
arr2 = np.mean(arr)
print(arr.mean())
arr1 = np.median(arr)
print(arr1)

[9 9 6 6 8 9 3 9 4 7 8 6 8 4 2]
6.533333333333333
7.0


In [27]:
arr = np.random.randint(1, 100, size=(3 , 4))

print(arr.min())
print(arr.max())

22
88


In [34]:
arr = np.random.randint(1, 10, size=(3 , 4))
print(arr)
print(arr + 1 )

[[7 2 5 6]
 [1 8 2 6]
 [4 6 9 4]]
[[ 8  3  6  7]
 [ 2  9  3  7]
 [ 5  7 10  5]]


In [37]:
arr = np.random.randint(1, 100, size=(3 , 4))

print(arr)

print(arr * arr)

[[76 22 51 40]
 [70 43 30  7]
 [19 29 66 35]]
[[5776  484 2601 1600]
 [4900 1849  900   49]
 [ 361  841 4356 1225]]
